version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: a509_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: a509_db
    ports:
      - "3306:3306"